version: '3.9'

services:

  postgres_db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: docker_example
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # app1:
  #   # image: jeziel/dockerexample:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   hostname: app1
  #   environment:
  #     HTTP_PORT: 8080
  #     DB_POSTGRES_PASSWORD: postgres
  #     DB_POSTGRES_USER: postgres
  #     DB_POSTGRES_DB: docker_example
  #     DB_POSTGRES_HOST: postgres_db
  #     DB_POSTGRES_PORT: 5432
  #   restart: always
  #   expose:
  #     - "8080"
  #   depends_on:
  #     - postgres_db
  # app2:
  #   # image: jeziel/dockerexample:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   hostname: app2
  #   environment:
  #     HTTP_PORT: 8080
  #     DB_POSTGRES_PASSWORD: postgres
  #     DB_POSTGRES_USER: postgres
  #     DB_POSTGRES_DB: docker_example
  #     DB_POSTGRES_HOST: postgres_db
  #     DB_POSTGRES_PORT: 5432
  #   restart: always
  #   expose:
  #     - "8080"
  #   depends_on:
  #     - postgres_db