version: '3.9'

services:
  postgres:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: docker_example
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  app1:
    # image: jeziel/dockerexample:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app1
    environment:
      PORT: 8081
      DB_POSTGRES_PASSWORD: postgres
      DB_POSTGRES_USER: postgres
      DB_POSTGRES_DB: docker_example
      DB_POSTGRES_HOST: db
      ENVIRONMENT: dev
      DB_POSTGRES_PORT: 5432
    restart: always
    ports:
      - 8080:8081
    depends_on:
      postgres:
        condition: service_healthy