version: '3.9'

services:
  postgres:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: docker_example
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.5GB'

  app1: &app
    # image: jeziel/dockerexample:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app1
    environment:
      PORT: 8080
      DB_POSTGRES_PASSWORD: postgres
      DB_POSTGRES_USER: postgres
      DB_POSTGRES_DB: docker_example
      DB_POSTGRES_HOST: db
      ENVIRONMENT: dev
      DB_POSTGRES_PORT: 5432
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '0.5GB'
  
  app2:
    <<: *app
    hostname: app2

  nginx:
    image: nginx:latest
    hostname: api
    volumes:
      - ./scripts/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    expose:
      - 9999
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '0.5GB'