# Create person
# @name createPerson
POST http://localhost:9999/pessoas  HTTP/1.1
Content-Type: application/json

{
    "apelido": "apelido-8",
    "nome": "nome-7",
    "nascimento": "1994-11-25",
    "stack": [
        "golang"
    ]
}

###

@personID = {{createPerson.response.headers.Location}}
# Get person by id
# @getPersonByID
GET http://localhost:9999/pessoas/{{personID}} HTTP/1.1
Content-Type: application/application/json

###

# Get person by id
# @getPersonByTerm
GET http://localhost:9999/pessoas?t={{personID}} HTTP/1.1
Content-Type: application/application/json

###

# Count person
# @name countPerson
GET http://localhost:9999/contagem-pessoas HTTP/1.1
Content-Type: application/application/json